server:
  port: 5000

admin:
  username: ${DEV_ADMIN_USERNAME}
  password: ${DEV_ADMIN_PASSWORD}

edgar:
  user_agent: ${DEV_EDGAR_USER_AGENT}
  form_batch_size: 250
  form_auto_load: false

spring.datasource:
  url: jdbc:h2:mem:db
  username: sa
  password: password
  driver-class-name: org.h2.Driver
