#!/bin/sh

# e.g. "sh deploy.sh 0.0.1"

# -- required env vars --
# S3_BUCKET - S3 bucket name generated by AWS

. ./.env.sh

APP_NAME=follow-insider
VERSION=$APP_NAME-source-$1
ENV_NAME=$APP_NAME-eb-env
S3_ASSET=core.jar

# build the web app
gradle build

# upload the web jar file to S3
aws s3 cp core/build/libs/$S3_ASSET s3://"$S3_BUCKET"/

# create a new version of the application
aws elasticbeanstalk create-application-version \
  --application-name $APP_NAME \
  --version-label "$VERSION" \
  --source-bundle S3Bucket="$S3_BUCKET",S3Key=$S3_ASSET

# update the environment to use the new version
aws elasticbeanstalk update-environment \
  --application-name $APP_NAME \
  --environment-name $ENV_NAME \
  --version-label "$VERSION"
