server:
  port: 5000

admin:
  username: ${DEV_ADMIN_USERNAME}
  password: ${DEV_ADMIN_PASSWORD}

edgar:
  user_agent: ${EDGAR_USER_AGENT}
  form_batch_size: 250
  form_auto_load: false

spring.datasource:
  url: ${DEV_DB_URL}
  username: ${DEV_DB_USERNAME}
  password: ${DEV_DB_PASSWORD}
  driver-class-name: ${DEV_DB_DRIVER}
